### ISSUE TITLE
Route all sync traffic through a single SSH socket

### ISSUE THREAD

**Issue by FranciscoSilveira** [opprDev/SimpleCloud#5]
Rsync can run through a single SSH tunnel:
https://ubuntuforums.org/showthread.php?t=2047378
Investigate possibility of using a single socket for data+messages (unlikely) or two sockets, one for Rsync (probably unnecessary since rsync already creates one, but will probably speed thing up a bit) and one for messages (following the SimpleCloud philosophy of not reinventing amazing wheels).

**Comment by FranciscoSilveira** [comment]
For future reference, this works:
ssh francisco@latticework.ddns.net -L 3555:latticework.ddns.net:22 -fN
rsync -av -e "ssh -p 3555" ~/temp/a/ francisco@localhost:~

**Comment by tomaspinho** [comment]
You may consider using the Bittorrent protocol with encryption as an alternative to rsync over SSH. You'll achieve better performance and speeds.
